"""added house img, email, and phone columns

Revision ID: 7e8a36d3a696
Revises: 7a3229f291db
Create Date: 2023-10-18 11:16:32.748479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e8a36d3a696'
down_revision = '7a3229f291db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('houses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('house_img', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone')
        batch_op.drop_column('email')

    with op.batch_alter_table('houses', schema=None) as batch_op:
        batch_op.drop_column('house_img')

    # ### end Alembic commands ###
